spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
      driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # 로그파일로 남길 수 있음. sql을
  #org.hibernate.type: trace # 파라미터까지 다 볼 수 있음. ? ? 이거 안떠!